name: Build Executables

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [created]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            output_name: crust-file-status-checker-linux
          - os: windows-latest
            output_name: crust-file-status-checker-win.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build executables
      run: npm run build

    # For Linux, we need to handle both x64 and ARM64 binaries
    - name: Rename Linux binaries
      if: matrix.os == 'ubuntu-latest'
      run: |
        mkdir -p dist
        cp crust-file-status-checker-linux-x64 dist/crust-file-status-checker-linux-x64
        cp crust-file-status-checker-linux-arm64 dist/crust-file-status-checker-linux-arm64
      shell: bash

    # For Windows, we have just the x64 binary
    - name: Rename Windows binary
      if: matrix.os == 'windows-latest'
      run: |
        mkdir -p dist
        copy crust-file-status-checker-win-x64.exe dist\crust-file-status-checker-win-x64.exe
      shell: cmd

    # Upload artifacts for each build
    - name: Upload Linux x64 artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: crust-file-status-checker-linux-x64
        path: dist/crust-file-status-checker-linux-x64

    - name: Upload Linux ARM64 artifact
      if: matrix.os == 'ubuntu-latest'
      uses: actions/upload-artifact@v4
      with:
        name: crust-file-status-checker-linux-arm64
        path: dist/crust-file-status-checker-linux-arm64

    - name: Upload Windows artifact
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: crust-file-status-checker-win-x64
        path: dist/crust-file-status-checker-win-x64.exe

  # Optional job to create a release with the binaries
  release:
    name: Attach binaries to release
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release'
    
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/crust-file-status-checker-linux-x64/crust-file-status-checker-linux-x64
            artifacts/crust-file-status-checker-linux-arm64/crust-file-status-checker-linux-arm64
            artifacts/crust-file-status-checker-win-x64/crust-file-status-checker-win-x64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
